package co.edu.icesi.academ.client;

import java.io.File;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.FileResource;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinService;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;

public class PanelPieDePagina extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Embedded footerImage;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelPieDePagina() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		// Find the application directory
		String basepath = VaadinService.getCurrent().getBaseDirectory().getAbsolutePath();

		// Image as a file resource
		FileResource footerResource = new FileResource(new File(basepath + "/WEB-INF/images/footer.png"));
		footerImage.setSource(footerResource);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
//		mainLayout.setWidth("982px");
		mainLayout.setHeight("70px");
		
		// top-level component properties
//		setWidth("982px");
		setWidth("100.0%");
		setHeight("70px");
		
		// footerImage
		footerImage = new Embedded();
		footerImage.setImmediate(false);
		footerImage.setWidth("982px");
		footerImage.setHeight("70px");
		footerImage.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		footerImage.setType(1);
		footerImage.setMimeType("image/png");
		mainLayout.addComponent(footerImage, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

}
