/**
* Copyright © 2013 Universidad Icesi
* 
* This file is part of ACADEM.
* 
* ACADEM is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* ACADEM is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with ACADEM.  If not, see <http://www.gnu.org/licenses/>.
**/

package co.edu.icesi.academ.client.perfiles.administrador;

import java.util.ArrayList;
import java.util.List;

import co.edu.icesi.academ.bo.BloqueBO;
import co.edu.icesi.academ.bo.MateriaBO;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;

public class PanelListaMateriasParaEditar extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table tableMaterias;
	@AutoGenerated
	private Button btn_editar;
	private List<MateriaBO>listMaterias;
	
	private BloqueBO bloqueBO;
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelListaMateriasParaEditar(final BloqueBO bloqueBO) {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.bloqueBO = bloqueBO;
		
		btn_editar.setEnabled(false);
		
		tableMaterias.addContainerProperty("Materias", MateriaBO.class, null);
		tableMaterias.setSelectable(true);
		tableMaterias.setImmediate(true);
		
		tableMaterias.addValueChangeListener(new ValueChangeListener() {			
			private static final long serialVersionUID = 1L;
			@Override
			public void valueChange(ValueChangeEvent event) {
				btn_editar.setEnabled(tableMaterias.getValue()!=null);
			}
		});
		
		btn_editar.addClickListener(new ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				try {
					int i = Integer.parseInt(tableMaterias.getValue().toString());
					ControladorAdministrador.getInstance().getAcademUI().cerrarVentanaEmergente();
					ControladorAdministrador.getInstance().mostrarPanelEditarMateria(listMaterias.get(i),bloqueBO);
				} catch (Exception e) {
					
				}					
			}
		});
	}
	
	public void cargarMaterias(List<MateriaBO>listMaterias) {
		this.listMaterias = new ArrayList<>();
		tableMaterias.removeAllItems();
		this.listMaterias = listMaterias;
		for (int i = 0; i < this.listMaterias.size(); i++) {
			MateriaBO bloqueBO = listMaterias.get(i);
			tableMaterias.addItem(new Object[] {bloqueBO}, new Integer(i));
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("400px");
		mainLayout.setHeight("300px");
		
		// top-level component properties
		setWidth("400px");
		setHeight("300px");
		
		// btn_editar
		btn_editar = new Button();
		btn_editar.setCaption("Editar");
		btn_editar.setImmediate(true);
		btn_editar.setWidth("280px");
		btn_editar.setHeight("-1px");
		mainLayout.addComponent(btn_editar, "top:234.0px;left:60.0px;");
		
		// tableMaterias
		tableMaterias = new Table();
		tableMaterias.setImmediate(false);
		tableMaterias.setWidth("100.0%");
		tableMaterias.setHeight("200px");
		mainLayout.addComponent(tableMaterias,
				"top:20.0px;right:60.0px;left:60.0px;");
		
		return mainLayout;
	}

}
