package co.edu.icesi.academ.client;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

public class PanelContenido extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelContenido() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	/***
	 * Agrega un componente al panel de contenido.
	 * @param component
	 */
	public void setContenido(CustomComponent component) {
		this.mainLayout.addComponent(component);
	}
	
	/***
	 * Agrega un componente al panel de contenido en una posición dada.
	 * @param component El componente a agregar.
	 * @param cssPosition La posición del componente.
	 */
	public void setContenido(CustomComponent component, String cssPosition) {
		this.mainLayout.addComponent(component, cssPosition);
	}
	
	/***
	 * Remueve todo el contenido del panel de contenido.
	 */
	public void removerTodoElContenido() {
		this.mainLayout.removeAllComponents();
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("500px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("500px");
		
		return mainLayout;
	}

}
