package co.edu.icesi.academ.client.usuarios;

import co.edu.icesi.academ.bo.UsuarioBO;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.UserError;
import com.vaadin.server.AbstractErrorMessage.ContentMode;
import com.vaadin.server.ErrorMessage.ErrorLevel;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class FormularioInicioSesion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label labelError;
	@AutoGenerated
	private Button botonIniciarSesion;
	@AutoGenerated
	private Label labelContraseña;
	@AutoGenerated
	private PasswordField fieldContraseña;
	@AutoGenerated
	private Label labelUsuario;
	@AutoGenerated
	private TextField fieldUsuario;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param request 
	 */
	@SuppressWarnings("serial")
	public FormularioInicioSesion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.botonIniciarSesion.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				iniciarSesion();
			}
		});
		
		this.labelError.setValue("");
		this.labelError.setEnabled(false);
	}

	protected void iniciarSesion() {
		UsuarioBO usuarioBO = new UsuarioBO();
		usuarioBO.setNombre(this.fieldUsuario.getValue());
		usuarioBO.setContraseña(this.fieldContraseña.getValue());
		ControladorInicioSesion.getInstance().iniciarSesion(usuarioBO);
	}
	
	public void setMensajeError(String mensaje) {
		Notification.show("ACaDeM", mensaje, Type.TRAY_NOTIFICATION);
		this.labelError.setValue(mensaje);
		this.botonIniciarSesion.setComponentError(new UserError(mensaje, ContentMode.TEXT, ErrorLevel.WARNING));
	}
	
	public void clear() {
		this.fieldUsuario.setValue("");
		this.fieldContraseña.setValue("");
		this.labelError.setValue("");
		this.botonIniciarSesion.setComponentError(null);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("340px");
		mainLayout.setHeight("180px");
		
		// top-level component properties
		setWidth("340px");
		setHeight("180px");
		
		// usernameField
		fieldUsuario = new TextField();
		fieldUsuario.setImmediate(false);
		fieldUsuario.setWidth("210px");
		fieldUsuario.setHeight("-1px");
		mainLayout.addComponent(fieldUsuario, "top:20.0px;left:100.0px;");
		
		// usernameLabel
		labelUsuario = new Label();
		labelUsuario.setImmediate(false);
		labelUsuario.setWidth("-1px");
		labelUsuario.setHeight("-1px");
		labelUsuario.setValue("Username:");
		mainLayout.addComponent(labelUsuario, "top:22.0px;left:20.0px;");
		
		// passwordField
		fieldContraseña = new PasswordField();
		fieldContraseña.setImmediate(false);
		fieldContraseña.setWidth("210px");
		fieldContraseña.setHeight("-1px");
		mainLayout.addComponent(fieldContraseña, "top:56.0px;left:100.0px;");
		
		// passwordLabel
		labelContraseña = new Label();
		labelContraseña.setImmediate(false);
		labelContraseña.setWidth("-1px");
		labelContraseña.setHeight("-1px");
		labelContraseña.setValue("Password:");
		mainLayout.addComponent(labelContraseña, "top:60.0px;left:20.0px;");
		
		// loginButton
		botonIniciarSesion = new Button();
		botonIniciarSesion.setCaption("Sign in");
		botonIniciarSesion.setImmediate(true);
		botonIniciarSesion.setWidth("-1px");
		botonIniciarSesion.setHeight("-1px");
		mainLayout.addComponent(botonIniciarSesion, "top:94.0px;left:209.0px;");
		
		// errorLabel
		labelError = new Label();
		labelError.setImmediate(false);
		labelError.setWidth("-1px");
		labelError.setHeight("-1px");
		mainLayout.addComponent(labelError, "top:142.0px;left:20.0px;");
		
		return mainLayout;
	}

}
