/**
* Copyright © 2013 Universidad Icesi
* 
* This file is part of ACADEM.
* 
* ACADEM is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* ACADEM is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with ACADEM.  If not, see <http://www.gnu.org/licenses/>.
**/

package co.edu.icesi.academ.client.usuarios;

import co.edu.icesi.academ.bo.UsuarioBO;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.AbstractErrorMessage.ContentMode;
import com.vaadin.server.ErrorMessage.ErrorLevel;
import com.vaadin.server.UserError;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;

public class FormularioInicioSesion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label labelError;
	@AutoGenerated
	private Button buttonIniciarSesion;
	@AutoGenerated
	private Label labelPassword;
	@AutoGenerated
	private PasswordField fieldContraseña;
	@AutoGenerated
	private Label labelUsuario;
	@AutoGenerated
	private TextField fieldUsuario;
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param request 
	 */
	@SuppressWarnings("serial")
	public FormularioInicioSesion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// User code
		this.buttonIniciarSesion.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				iniciarSesion();
			}
		});
		
		this.labelError.setValue("");
		this.labelError.setEnabled(false);
	}

	protected void iniciarSesion() {
		UsuarioBO usuarioBO = new UsuarioBO();
		usuarioBO.setNombre(this.fieldUsuario.getValue());
		usuarioBO.setContraseña(this.fieldContraseña.getValue());
		ControladorInicioSesion.getInstance().iniciarSesion(usuarioBO);
	}
	
	public void setMensajeError(String mensaje) {
		Notification.show("ACaDeM", mensaje, Type.TRAY_NOTIFICATION);
		this.labelError.setValue(mensaje);
		this.buttonIniciarSesion.setComponentError(new UserError(mensaje, ContentMode.TEXT, ErrorLevel.WARNING));
	}
	
	public void clear() {
		this.fieldUsuario.setValue("");
		this.fieldContraseña.setValue("");
		this.labelError.setValue("");
		this.buttonIniciarSesion.setComponentError(null);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("340px");
		mainLayout.setHeight("180px");
		
		// top-level component properties
		setWidth("340px");
		setHeight("180px");
		
		// fieldUsuario
		fieldUsuario = new TextField();
		fieldUsuario.setImmediate(false);
		fieldUsuario.setWidth("210px");
		fieldUsuario.setHeight("-1px");
		mainLayout.addComponent(fieldUsuario, "top:20.0px;left:100.0px;");
		
		// labelUsuario
		labelUsuario = new Label();
		labelUsuario.setImmediate(false);
		labelUsuario.setWidth("-1px");
		labelUsuario.setHeight("-1px");
		labelUsuario.setValue("Usuario:");
		mainLayout.addComponent(labelUsuario, "top:22.0px;left:20.0px;");
		
		// fieldPassword
		fieldContraseña = new PasswordField();
		fieldContraseña.setImmediate(false);
		fieldContraseña.setWidth("210px");
		fieldContraseña.setHeight("-1px");
		mainLayout.addComponent(fieldContraseña, "top:56.0px;left:100.0px;");
		
		// labelContrasea
		labelPassword = new Label();
		labelPassword.setImmediate(false);
		labelPassword.setWidth("-1px");
		labelPassword.setHeight("-1px");
		labelPassword.setValue("Contraseña:");
		mainLayout.addComponent(labelPassword, "top:60.0px;left:20.0px;");
		
		// botonIniciarSesion
		buttonIniciarSesion = new Button();
		buttonIniciarSesion.setCaption("Iniciar Sesión");
		buttonIniciarSesion.setImmediate(true);
		buttonIniciarSesion.setWidth("101px");
		buttonIniciarSesion.setHeight("-1px");
		mainLayout.addComponent(buttonIniciarSesion, "top:94.0px;right:30.0px;");
		
		// labelError
		labelError = new Label();
		labelError.setImmediate(false);
		labelError.setWidth("-1px");
		labelError.setHeight("-1px");
		labelError.setValue("Label");
		mainLayout.addComponent(labelError, "top:142.0px;left:20.0px;");
		
		return mainLayout;
	}

}
