package co.edu.icesi.academ.client.usuarios;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

public class PanelSesion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label labelNombreUsuario;
	@AutoGenerated
	private Button botonCerrarSesion;
	private static final long serialVersionUID = 1L;
	private ControladorInicioSesion controladorInicioSesion;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelSesion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		this.controladorInicioSesion = ControladorInicioSesion.getInstance();
		
		this.labelNombreUsuario.setValue("");
		
		this.botonCerrarSesion.addClickListener(new ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				cerrarSesion();
			}
		});
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.labelNombreUsuario.setValue("Usuario: " + nombreUsuario);
	}

	protected void cerrarSesion() {
		this.controladorInicioSesion.cerrarSesion();
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("300px");
		mainLayout.setHeight("60px");
		
		// top-level component properties
		setWidth("300px");
		setHeight("60px");
		
		// botonCerrarSesion
		botonCerrarSesion = new Button();
		botonCerrarSesion.setCaption("Cerrar Sesión");
		botonCerrarSesion.setImmediate(true);
		botonCerrarSesion.setWidth("-1px");
		botonCerrarSesion.setHeight("-1px");
		mainLayout.addComponent(botonCerrarSesion, "top:14.0px;left:20.0px;");
		
		// labelNombreUsuario
		labelNombreUsuario = new Label();
		labelNombreUsuario.setImmediate(false);
		labelNombreUsuario.setWidth("-1px");
		labelNombreUsuario.setHeight("-1px");
		labelNombreUsuario.setValue("Label");
		mainLayout.addComponent(labelNombreUsuario, "top:20.0px;left:140.0px;");
		
		return mainLayout;
	}

}
