/**
* Copyright © 2013 Universidad Icesi
* 
* This file is part of ACADEM.
* 
* ACADEM is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* ACADEM is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with ACADEM.  If not, see <http://www.gnu.org/licenses/>.
**/

package co.edu.icesi.academ.client.usuarios;

import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

public class PanelSesion extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button buttonCambiarPerfil;
	@AutoGenerated
	private ComboBox comboBoxPerfil;
	@AutoGenerated
	private Label labelNombreUsuario;
	@AutoGenerated
	private Button buttonCerrarSesion;
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelSesion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// User code
		this.labelNombreUsuario.setValue("");
		
		this.comboBoxPerfil.setNullSelectionAllowed(false);
		this.comboBoxPerfil.setTextInputAllowed(false);
		
		this.buttonCambiarPerfil.addClickListener(new ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				cambiarPerfil();
			}
		});
		
		this.buttonCerrarSesion.addClickListener(new ClickListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				cerrarSesion();
			}
		});
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.labelNombreUsuario.setValue("Usuario: " + nombreUsuario);
	}
	
	public void setPerfiles(List<String> perfiles) {
		for (String perfil : perfiles) 
		{
			this.comboBoxPerfil.addItem(perfil);
		}
	}
	
	public void seleccionarPerfil(String perfil) {
		this.comboBoxPerfil.select(perfil);
	}

	protected void cambiarPerfil() {
		String perfil = (String) this.comboBoxPerfil.getValue();
		ControladorInicioSesion.getInstance().cambiarPerfilA(perfil);
	}

	protected void cerrarSesion() {
		ControladorInicioSesion.getInstance().cerrarSesion();
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("60px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("60px");
		
		// botonCerrarSesion
		buttonCerrarSesion = new Button();
		buttonCerrarSesion.setCaption("Cerrar Sesión");
		buttonCerrarSesion.setImmediate(true);
		buttonCerrarSesion.setWidth("101px");
		buttonCerrarSesion.setHeight("-1px");
		mainLayout.addComponent(buttonCerrarSesion, "top:20.0px;right:19.0px;");
		
		// labelNombreUsuario
		labelNombreUsuario = new Label();
		labelNombreUsuario.setImmediate(false);
		labelNombreUsuario.setWidth("-1px");
		labelNombreUsuario.setHeight("-1px");
		labelNombreUsuario.setValue("Label");
		mainLayout
				.addComponent(labelNombreUsuario, "top:22.0px;right:533.0px;");
		
		// comboBoxPerfil
		comboBoxPerfil = new ComboBox();
		comboBoxPerfil.setImmediate(false);
		comboBoxPerfil.setWidth("158px");
		comboBoxPerfil.setHeight("-1px");
		mainLayout.addComponent(comboBoxPerfil, "top:20.0px;right:142.0px;");
		
		// buttonCambiarPerfil
		buttonCambiarPerfil = new Button();
		buttonCambiarPerfil.setCaption("Cambiar Perfil A:");
		buttonCambiarPerfil.setImmediate(false);
		buttonCambiarPerfil.setWidth("117px");
		buttonCambiarPerfil.setHeight("-1px");
		mainLayout.addComponent(buttonCambiarPerfil,
				"top:18.0px;right:317.0px;");
		
		return mainLayout;
	}

}
