/**
* Copyright © 2013 Universidad Icesi
* 
* This file is part of ACADEM.
* 
* ACADEM is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* ACADEM is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with ACADEM.  If not, see <http://www.gnu.org/licenses/>.
**/

package co.edu.icesi.academ.client.perfiles;

import java.text.SimpleDateFormat;
import java.util.List;

import co.edu.icesi.academ.bo.EvaluacionBO;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class ListadoEvaluaciones extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Panel panelTitulo;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Label labelTitulo;
	@AutoGenerated
	private Table tablaEvaluaciones;
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ListadoEvaluaciones() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// User code
		
		// Define the names and data types of columns.
		tablaEvaluaciones.addContainerProperty("ID", Integer.class, null);
		tablaEvaluaciones.addContainerProperty("Fecha Inicial", String.class, null);
		tablaEvaluaciones.addContainerProperty("Fecha Final", String.class, null);
		tablaEvaluaciones.addContainerProperty("Programa", String.class, null);

		// Allow selecting items from the table.
		tablaEvaluaciones.setSelectable(true);
		
		// Send changes in selection immediately to server.
		tablaEvaluaciones.setImmediate(true);
		
		// Handle selection change.
		tablaEvaluaciones.addValueChangeListener(new ValueChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				seleccionarEvaluacion();
			}
		});
	}
	
	protected void seleccionarEvaluacion() {
		EvaluacionBO evaluacionBO = (EvaluacionBO) tablaEvaluaciones.getValue();
		ControladorEvaluaciones.getInstance().seleccionarEvaluación(evaluacionBO);
	}

	public void cargarEvaluaciones(List<EvaluacionBO> evaluaciones) {
		tablaEvaluaciones.removeAllItems();
		
		if (evaluaciones != null) {
			SimpleDateFormat dateFormat = new SimpleDateFormat ("dd-MM-yyyy");
			for (EvaluacionBO evaluacion : evaluaciones) {
				tablaEvaluaciones.addItem(new Object[]{ evaluacion.getId(), dateFormat.format(evaluacion.getFechaInicial()), dateFormat.format(evaluacion.getFechaFinal()), evaluacion.getPrograma().getNombre() }, evaluacion);
			}
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("300px");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("300px");
		setHeight("100.0%");
		
		// tablaEvaluaciones
		tablaEvaluaciones = new Table();
		tablaEvaluaciones.setImmediate(false);
		tablaEvaluaciones.setWidth("300px");
		tablaEvaluaciones.setHeight("100.0%");
		mainLayout.addComponent(tablaEvaluaciones,
				"top:48.0px;bottom:20.0px;left:0.0px;");
		
		// panelTitulo
		panelTitulo = buildPanelTitulo();
		mainLayout.addComponent(panelTitulo, "top:20.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanelTitulo() {
		// common part: create layout
		panelTitulo = new Panel();
		panelTitulo.setImmediate(false);
		panelTitulo.setWidth("300px");
		panelTitulo.setHeight("30px");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		panelTitulo.setContent(verticalLayout_1);
		
		return panelTitulo;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// labelTitulo
		labelTitulo = new Label();
		labelTitulo.setImmediate(false);
		labelTitulo.setWidth("-1px");
		labelTitulo.setHeight("-1px");
		labelTitulo.setValue("Evaluaciones");
		verticalLayout_1.addComponent(labelTitulo);
		verticalLayout_1.setComponentAlignment(labelTitulo, new Alignment(48));
		
		return verticalLayout_1;
	}

}
