package co.edu.icesi.academ.client.perfiles;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TabSheet.SelectedTabChangeEvent;
import com.vaadin.ui.TabSheet.SelectedTabChangeListener;

public class PanelOpciones extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheetOpciones;
	private static final long serialVersionUID = 1L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelOpciones() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		tabSheetOpciones.addSelectedTabChangeListener(new SelectedTabChangeListener() {
			
			private static final long serialVersionUID = 1L;

			@Override
			public void selectedTabChange(SelectedTabChangeEvent event) {
				
			}
		});
	}
	
	public TabSheet getTabSheetOpciones() {
		return tabSheetOpciones;
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheetOpciones
		tabSheetOpciones = new TabSheet();
		tabSheetOpciones.setImmediate(false);
		tabSheetOpciones.setWidth("100.0%");
		tabSheetOpciones.setHeight("100.0%");
		mainLayout.addComponent(tabSheetOpciones,
				"top:20.0px;bottom:20.0px;left:0.0px;");
		
		return mainLayout;
	}

}
